# Generated by Django 4.2.3 on 2023-08-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_comment_rename_rate_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commented_by',
        ),
    ]
