# Generated by Django 4.2.3 on 2023-08-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_rename_user_comment_commented_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='owner',
        ),
    ]
