# Generated by Django 4.2.3 on 2023-08-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='long',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='province',
            field=models.CharField(default='Lima', max_length=50),
            preserve_default=False,
        ),
    ]
