# Generated by Django 4.2.3 on 2023-08-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_delete_clubimage'),
        ('booking', '0002_alter_court_days_alter_court_end_alter_court_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='sports',
        ),
        migrations.AddField(
            model_name='court',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='club.sport'),
        ),
    ]
