# Generated by Django 4.2.3 on 2023-08-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Jugador'), ('organizer', 'Organizador'), ('referee', 'Arbitro'), ('admin', 'Administrador')], default='player', max_length=20),
        ),
    ]
