# Generated by Django 4.2.3 on 2023-08-01 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=5)]),
        ),
    ]
