# Generated by Django 4.2.3 on 2023-07-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_created_at_publication_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
