# Generated by Django 4.2.3 on 2023-08-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubImage',
        ),
    ]
