# Generated by Django 4.2.3 on 2023-08-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
