# Generated by Django 4.2.3 on 2023-09-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='members',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='membership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='club.club'),
        ),
    ]
