# Generated by Django 4.2.3 on 2023-08-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_club_members_alter_club_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
