# Generated by Django 4.2.3 on 2023-08-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_club_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='member',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
    ]
