# Generated by Django 4.2.1 on 2023-06-07 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('address', models.CharField(max_length=300)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_local', to='club.club')),
                ('referees', models.ManyToManyField(related_name='matches_observed', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_visitor', to='club.club')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='club.club')),
            ],
        ),
    ]
