# Generated by Django 4.2.3 on 2023-09-02 03:46

from django.db import migrations, models
import django.db.models.deletion
import match.validators


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='local',
        ),
        migrations.RemoveField(
            model_name='match',
            name='visitor',
        ),
        migrations.CreateModel(
            name='MatchClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField(default=False)),
                ('club', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('match', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='match.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='clubs',
            field=models.ManyToManyField(
                related_name='matches', through='match.MatchClub', to='club.club'),
        ),
    ]
