# Generated by Django 4.2.3 on 2023-09-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('match', '0002_remove_match_local_remove_match_visitor_matchclub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='clubs',
            field=models.ManyToManyField(related_name='matches', through='match.MatchClub', to='club.club'),
        ),
    ]
