# Generated by Django 4.2.3 on 2023-09-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_match_clubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
    ]
