# Generated by Django 4.2.3 on 2023-09-02 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0004_remove_match_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assited', models.BooleanField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.AlterField(
            model_name='matchclub',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_clubs', to='match.match'),
        ),
        migrations.DeleteModel(
            name='MatchPlayer',
        ),
        migrations.AddField(
            model_name='matchclubuser',
            name='match_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.matchclub'),
        ),
        migrations.AddField(
            model_name='matchclubuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchclub',
            name='players',
            field=models.ManyToManyField(related_name='match_clubs', through='match.MatchClubUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
