# Generated by Django 4.2.3 on 2023-09-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_matchclubuser_remove_match_players_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchclubuser',
            old_name='assited',
            new_name='assisted',
        ),
    ]
