# Generated by Django 4.2.3 on 2023-09-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_rename_assited_matchclubuser_assisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchclub',
            name='challenger',
            field=models.BooleanField(default=False),
        ),
    ]
